import Head from "next/head"
import Banner from "../modules/banner/Banner"
import { Card } from "../modules/cards/Card"
import Footer from "../modules/footer/Footer"
import Header from "../modules/header/Header"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <Card />
      <Footer />
    </div>
  )
}
